priordump: 50x3_3_100k_classification.h5
heads: 6
embeddingsize: 192
hiddensize: 768
layers: 6
batchsize: 1
accumulate: 1
lr: 0.0001
steps: 100
epochs: 10000
loadcheckpoint: null
multigpu: false
runname: nanotabpfn
