priordump: 50x3_3_100k_classification.h5
embeddingsize: 128
colblocks: 3
rowblocks: 3
iclblocks: 12
colheads: 8
rowheads: 8
iclheads: 8
featuregroupsize: 3
clscols: 4
clsrows: 128
batchsize: 1
accumulate: 1
lr: 0.0001
steps: 100
epochs: 10000
multigpu: false
